### ISSUE TITLE
node-red-contrib-get-hrefs 2.1.0 issue with prototype pollution ?

### ISSUE THREAD

**Issue by frownbreaker** [joakimbeng/get-hrefs#3]
Hi there I wanted you use the get href node but installing I got some errors around the use of loadash which has been updated to fix their bug. Not sure what's required to fix the node-red-contrib-get-hrefs

I think its only a minor security issue but thought I'd report it. 
https://www.npmjs.com/advisories/577

npm audit

                       === npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Low             Prototype Pollution

  Package         lodash

  Patched in      >=4.17.5

  Dependency of   node-red-contrib-get-hrefs

  Path            node-red-contrib-get-hrefs > get-hrefs > cheerio > lodash

  More info       https://nodesecurity.io/advisories/577

found 1 low severity vulnerability in 404 scanned packages
  1 vulnerability requires manual review. See the full report for details.

**Comment by frownbreaker** [comment]
Just looked at the code I think there is a cheerio library that may be the issue? I'm new to node-red so please forgive me if any of my "analysis" or conclusions are wrong. Thanks for a useful processing node :)

**Comment by joakimbeng** [comment]
No problem! Closing this then...
